#pragma once

#define DEVICE_PIC_MASTER_MASK 0xf8
#define DEVICE_PIC_SLAVE_MASK 0xbf

#define DEVICE_IDE_CHANNEL_NAME_SIZE 8

#define DEVICE_DISK_NAME_SIZE 8
#define DEVICE_DISK_KERNEL_INDEX 0

#define DEVICE_DISK_PARTITION_NAME_SIZE 8