#pragma once

#define DISK_PORT_DATA 0x1f0

#define DISK_CMD_SECS 0x1f2
#define DISK_CMD_LBALOW 0x1f3
#define DISK_CMD_LBAMID 0x1f4
#define DISK_CMD_LBAHIGH 0x1f5
#define DISK_CMD_LBAEX 0x1f6
#define DISK_CMD_CTRL 0x1f7

#define DISK_CMD_READ 0x20

#define DISK_STATUS_BUSY 0x80
#define DISK_STATUS_READY 0x40